import { Open_Sans } from 'next/font/google';
import Footer from './components/Footer';
import Header from './components/Header';
import { SearchProvider } from './hooks/SearchContext';
import { LectureProvider } from './hooks/LectureContext';
import { EdgeStoreProvider } from './hooks/edgestore';
import './globals.css';

const open_sans = Open_Sans({ subsets: ['hebrew'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	// const [searchObj, setSearchObj] = useState({ name: '', tags: new Set() });

	return (
		<html data-theme="light" lang="he">
			<body dir="rtl" className={open_sans.className}>
				<LectureProvider>
					<SearchProvider>
						<Header />
						<EdgeStoreProvider>{children}</EdgeStoreProvider>
						{/* {children} */}
						<Footer />
					</SearchProvider>
				</LectureProvider>
			</body>
		</html>
	);
}
