import { Inter } from 'next/font/google';
import Footer from './components/Footer';
import Header from './components/Header';
import { SearchProvider } from './hooks/SearchContext';
import { LectureProvider } from './hooks/LectureContext';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	// const [searchObj, setSearchObj] = useState({ name: '', tags: new Set() });

	return (
		<html data-theme="light" lang="he">
			<body dir="rtl" className={inter.className}>
				<LectureProvider>
					<SearchProvider>
						<Header />
						{children}
						<Footer />
					</SearchProvider>
				</LectureProvider>
			</body>
		</html>
	);
}
